### ISSUE TITLE
Readme file instructions do not work on Fedora 36 or Ubuntu 22.04

### ISSUE THREAD

**Issue by barrowsr** [compulab-yokneam/meta-mender-compulab#10]
Readme file does not work on Fedora 36 or Ubuntu 22.04

I installed all of the build packages specified on the build host:
https://docs.yoctoproject.org/brief-yoctoprojectqs/index.html

I tried both OS's and was unable to get bitbake to run.

```
[user:~/git/ … /build-mender-iot-gate-imx8] $ bitbake -k core-image-full-cmdline
Traceback (most recent call last):
  File "/home/user/git/iot-gate-imx8-yocto/mender-compulab/sources/poky/bitbake/bin/bitbake", line 19, in <module>
    import bb
  File "/home/user/git/iot-gate-imx8-yocto/mender-compulab/sources/poky/bitbake/lib/bb/__init__.py", line 74, in <module>
    import bb.msg
  File "/home/user/git/iot-gate-imx8-yocto/mender-compulab/sources/poky/bitbake/lib/bb/msg.py", line 20, in <module>
    import bb.event
  File "/home/user/git/iot-gate-imx8-yocto/mender-compulab/sources/poky/bitbake/lib/bb/event.py", line 23, in <module>
    import bb.compat
  File "/home/user/git/iot-gate-imx8-yocto/mender-compulab/sources/poky/bitbake/lib/bb/compat.py", line 7, in <module>
    from collections import MutableMapping, KeysView, ValuesView, ItemsView, OrderedDict
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)
```

Is there a preferred OS/OS Version to use to utilize this Readme?

Thanks!

**Comment by vraevsky** [comment]
Try docker: https://github.com/compulab-yokneam/yocker

BR.
